"""Static lexicons, persona definitions, and package-wide limits."""

from __future__ import annotations

import re
from typing import Any

# Weighted emotion lexicon: word → (emotion, weight)
# Each word can signal multiple emotions with different weights.
EMOTION_LEXICON: dict[str, list[tuple[str, float]]] = {
    # Joy / Happiness
    "happy": [("joy", 0.9)],
    "glad": [("joy", 0.7)],
    "delighted": [("joy", 0.85)],
    "excited": [("joy", 0.8), ("excitement", 0.9)],
    "thrilled": [("joy", 0.85), ("excitement", 0.9)],
    "wonderful": [("joy", 0.8)],
    "amazing": [("joy", 0.75)],
    "great": [("joy", 0.5)],
    "love": [("joy", 0.7), ("affection", 0.9)],
    "enjoy": [("joy", 0.6)],
    "pleased": [("joy", 0.65)],
    "cheerful": [("joy", 0.8)],
    "grateful": [("joy", 0.6), ("gratitude", 0.9)],
    "awesome": [("joy", 0.7)],
    "fantastic": [("joy", 0.8)],
    "beautiful": [("joy", 0.5)],
    # Sadness
    "sad": [("sadness", 0.9)],
    "unhappy": [("sadness", 0.8)],
    "miserable": [("sadness", 0.95)],
    "depressed": [("sadness", 0.9)],
    "heartbroken": [("sadness", 0.95)],
    "lonely": [("sadness", 0.8)],
    "grief": [("sadness", 0.95)],
    "loss": [("sadness", 0.7)],
    "disappointed": [("sadness", 0.7)],
    "hopeless": [("sadness", 0.85)],
    "crying": [("sadness", 0.9)],
    "tears": [("sadness", 0.8)],
    "mourn": [("sadness", 0.9)],
    # Anger
    "angry": [("anger", 0.9)],
    "furious": [("anger", 0.95)],
    "mad": [("anger", 0.7)],
    "annoyed": [("anger", 0.6)],
    "irritated": [("anger", 0.65)],
    "frustrated": [("anger", 0.7), ("frustration", 0.9)],
    "outraged": [("anger", 0.95)],
    "hate": [("anger", 0.85)],
    "resent": [("anger", 0.8)],
    "livid": [("anger", 0.95)],
    "bitter": [("anger", 0.7)],
    # Fear / Anxiety
    "afraid": [("fear", 0.9)],
    "scared": [("fear", 0.85)],
    "terrified": [("fear", 0.95)],
    "anxious": [("fear", 0.7), ("anxiety", 0.9)],
    "worried": [("fear", 0.6), ("anxiety", 0.8)],
    "nervous": [("fear", 0.7), ("anxiety", 0.75)],
    "panic": [("fear", 0.9)],
    "dread": [("fear", 0.85)],
    "uneasy": [("fear", 0.5), ("anxiety", 0.6)],
    "stress": [("anxiety", 0.8)],
    "stressed": [("anxiety", 0.85)],
    "overwhelmed": [("anxiety", 0.8)],
    # Trust / Warmth
    "trust": [("trust", 0.9)],
    "believe": [("trust", 0.6)],
    "reliable": [("trust", 0.7)],
    "honest": [("trust", 0.7)],
    "faith": [("trust", 0.8)],
    "safe": [("trust", 0.6)],
    # Surprise
    "surprised": [("surprise", 0.8)],
    "shocked": [("surprise", 0.9)],
    "unexpected": [("surprise", 0.7)],
    "astonished": [("surprise", 0.85)],
    "wow": [("surprise", 0.6)],
    "unbelievable": [("surprise", 0.7)],
    # Disgust
    "disgusted": [("disgust", 0.9)],
    "revolting": [("disgust", 0.9)],
    "gross": [("disgust", 0.7)],
    "repulsive": [("disgust", 0.85)],
    "sick": [("disgust", 0.5)],
    "nauseating": [("disgust", 0.8)],
    # Contempt
    "pathetic": [("contempt", 0.8)],
    "worthless": [("contempt", 0.7), ("sadness", 0.6)],
    "ridiculous": [("contempt", 0.6)],
    "stupid": [("contempt", 0.7), ("anger", 0.4)],
    # Confusion
    "confused": [("confusion", 0.9)],
    "lost": [("confusion", 0.6), ("sadness", 0.4)],
    "unclear": [("confusion", 0.7)],
    "puzzled": [("confusion", 0.8)],
    # Neutral / Cognitive
    "think": [("neutral", 0.3)],
    "know": [("neutral", 0.2)],
    "understand": [("neutral", 0.3)],
    "consider": [("neutral", 0.3)],
    "need": [("neutral", 0.2)],
    "want": [("neutral", 0.3)],
    "help": [("neutral", 0.2), ("anxiety", 0.2)],
    "please": [("neutral", 0.1)],
    "thanks": [("gratitude", 0.7), ("joy", 0.3)],
}

# Big Five trait indicator words with directional weights
BIG_FIVE_LEXICON: dict[str, dict[str, list[tuple[str, float]]]] = {
    "openness": {
        "high": [
            ("creative", 0.8),
            ("imagine", 0.7),
            ("innovative", 0.8),
            ("curious", 0.75),
            ("artistic", 0.7),
            ("philosophical", 0.8),
            ("abstract", 0.6),
            ("explore", 0.65),
            ("dream", 0.5),
            ("unique", 0.6),
            ("novel", 0.7),
            ("experiment", 0.7),
            ("wonder", 0.6),
            ("inspire", 0.6),
            ("visionary", 0.8),
            ("unconventional", 0.7),
            ("aesthetic", 0.7),
            ("poetic", 0.65),
            ("original", 0.7),
            ("idea", 0.4),
        ],
        "low": [
            ("traditional", 0.7),
            ("conventional", 0.7),
            ("practical", 0.5),
            ("routine", 0.6),
            ("standard", 0.5),
            ("proven", 0.4),
            ("familiar", 0.5),
            ("concrete", 0.4),
            ("realistic", 0.5),
            ("predictable", 0.5),
            ("established", 0.5),
            ("normal", 0.4),
        ],
    },
    "conscientiousness": {
        "high": [
            ("organized", 0.8),
            ("plan", 0.6),
            ("schedule", 0.7),
            ("careful", 0.7),
            ("detail", 0.6),
            ("thorough", 0.8),
            ("responsible", 0.7),
            ("disciplined", 0.8),
            ("precise", 0.7),
            ("systematic", 0.8),
            ("reliable", 0.6),
            ("prepared", 0.6),
            ("methodical", 0.8),
            ("diligent", 0.8),
            ("punctual", 0.7),
            ("efficient", 0.6),
        ],
        "low": [
            ("spontaneous", 0.7),
            ("flexible", 0.4),
            ("casual", 0.5),
            ("relaxed", 0.4),
            ("whatever", 0.6),
            ("improvise", 0.6),
            ("wing", 0.5),
            ("easygoing", 0.5),
            ("procrastinate", 0.8),
            ("messy", 0.7),
            ("careless", 0.7),
            ("lazy", 0.7),
        ],
    },
    "extraversion": {
        "high": [
            ("excited", 0.6),
            ("social", 0.8),
            ("party", 0.7),
            ("people", 0.4),
            ("outgoing", 0.85),
            ("energetic", 0.7),
            ("talkative", 0.8),
            ("lively", 0.7),
            ("enthusiastic", 0.7),
            ("gregarious", 0.9),
            ("bold", 0.6),
            ("fun", 0.5),
            ("crowd", 0.5),
            ("together", 0.3),
            ("friends", 0.4),
            ("loud", 0.5),
        ],
        "low": [
            ("quiet", 0.7),
            ("alone", 0.7),
            ("private", 0.7),
            ("introvert", 0.9),
            ("calm", 0.4),
            ("peaceful", 0.4),
            ("solitude", 0.8),
            ("reserved", 0.8),
            ("withdrawn", 0.7),
            ("shy", 0.7),
            ("silent", 0.6),
            ("reflective", 0.5),
        ],
    },
    "agreeableness": {
        "high": [
            ("help", 0.5),
            ("kind", 0.8),
            ("nice", 0.6),
            ("friendly", 0.7),
            ("cooperative", 0.8),
            ("understanding", 0.7),
            ("caring", 0.8),
            ("gentle", 0.7),
            ("compassionate", 0.85),
            ("generous", 0.7),
            ("empathetic", 0.8),
            ("warm", 0.6),
            ("supportive", 0.7),
            ("forgiving", 0.7),
            ("patient", 0.5),
            ("considerate", 0.7),
        ],
        "low": [
            ("compete", 0.6),
            ("win", 0.4),
            ("argue", 0.6),
            ("disagree", 0.5),
            ("conflict", 0.6),
            ("challenge", 0.5),
            ("dominate", 0.7),
            ("ruthless", 0.8),
            ("blunt", 0.6),
            ("harsh", 0.6),
            ("aggressive", 0.7),
            ("stubborn", 0.6),
        ],
    },
    "neuroticism": {
        "high": [
            ("worry", 0.8),
            ("stress", 0.7),
            ("anxious", 0.85),
            ("nervous", 0.8),
            ("upset", 0.7),
            ("emotional", 0.5),
            ("sensitive", 0.5),
            ("insecure", 0.8),
            ("tense", 0.7),
            ("vulnerable", 0.6),
            ("overwhelmed", 0.8),
            ("fragile", 0.7),
            ("moody", 0.7),
            ("unstable", 0.8),
            ("panic", 0.8),
            ("doubt", 0.6),
        ],
        "low": [
            ("calm", 0.7),
            ("stable", 0.8),
            ("relaxed", 0.6),
            ("confident", 0.7),
            ("secure", 0.7),
            ("composed", 0.8),
            ("steady", 0.7),
            ("resilient", 0.8),
            ("unflappable", 0.9),
            ("balanced", 0.6),
            ("centered", 0.7),
            ("grounded", 0.7),
        ],
    },
}

# Formality indicators
FORMALITY_MARKERS: dict[str, list[tuple[str, float]]] = {
    "formal": [
        ("therefore", 0.8),
        ("however", 0.7),
        ("furthermore", 0.8),
        ("consequently", 0.85),
        ("regarding", 0.7),
        ("nevertheless", 0.85),
        ("accordingly", 0.8),
        ("henceforth", 0.9),
        ("whereas", 0.7),
        ("hereby", 0.9),
        ("pursuant", 0.9),
        ("moreover", 0.75),
        ("shall", 0.7),
        ("whom", 0.7),
        ("thus", 0.7),
        ("indeed", 0.5),
    ],
    "informal": [
        ("gonna", 0.9),
        ("wanna", 0.9),
        ("gotta", 0.9),
        ("kinda", 0.8),
        ("yeah", 0.7),
        ("nah", 0.8),
        ("cool", 0.5),
        ("awesome", 0.5),
        ("stuff", 0.5),
        ("lol", 0.9),
        ("omg", 0.9),
        ("btw", 0.9),
        ("hey", 0.6),
        ("yo", 0.8),
        ("dude", 0.8),
        ("bro", 0.8),
        ("haha", 0.7),
        ("ok", 0.3),
        ("nope", 0.7),
        ("yep", 0.7),
    ],
}

# Directness indicators
DIRECTNESS_MARKERS: dict[str, list[tuple[str, float]]] = {
    "direct": [
        ("need", 0.5),
        ("want", 0.5),
        ("must", 0.7),
        ("now", 0.4),
        ("immediately", 0.8),
        ("exactly", 0.6),
        ("specifically", 0.6),
        ("require", 0.7),
        ("demand", 0.8),
        ("insist", 0.8),
    ],
    "indirect": [
        ("maybe", 0.7),
        ("perhaps", 0.7),
        ("possibly", 0.7),
        ("might", 0.5),
        ("could", 0.4),
        ("wondering", 0.7),
        ("suggest", 0.5),
        ("consider", 0.4),
        ("seems", 0.5),
        ("appears", 0.5),
        ("somewhat", 0.6),
        ("slightly", 0.6),
    ],
}

# Discourse markers for topic transitions
DISCOURSE_MARKERS = {
    "continuation": [
        "Building on that,",
        "Along those lines,",
        "Expanding on that thought,",
        "In that same vein,",
        "Continuing with that,",
        "",
    ],
    "shift": [
        "On a different note,",
        "Shifting gears a bit,",
        "That reminds me —",
        "Speaking of which,",
        "Moving to another point,",
        "Incidentally,",
    ],
    "return": [
        "Coming back to what we discussed about {topic},",
        "Returning to {topic},",
        "Going back to our earlier point about {topic},",
        "Revisiting {topic} for a moment,",
    ],
}

# Disfluency patterns by type
DISFLUENCY_PATTERNS = {
    "filled_pause": ["um", "uh", "er", "ah", "mm"],
    "filler_word": ["like", "you know", "actually", "basically", "I mean", "sort of", "kind of"],
    "hesitation": ["well", "so", "let me think", "hmm"],
    "repair_prefix": ["I mean", "or rather", "that is", "actually", "well no"],
    "false_start_connectors": ["—", "—", "actually,", "wait,"],
}
VALID_MEMORY_TYPES = {"episodic", "semantic", "procedural", "emotional"}
TOKEN_CLEANUP_RE = re.compile(r"^[^\w]+|[^\w]+$")
FIRST_PERSON_PRONOUNS = {"i", "me", "my", "mine", "myself", "we", "us", "our", "ours"}
HEDGE_WORDS = {
    "maybe",
    "perhaps",
    "possibly",
    "might",
    "could",
    "seems",
    "appears",
    "somewhat",
    "rather",
    "arguably",
    "presumably",
    "allegedly",
    "apparently",
}
INTENSIFIER_WORDS = {
    "very",
    "really",
    "extremely",
    "absolutely",
    "totally",
    "completely",
    "utterly",
    "incredibly",
    "remarkably",
    "deeply",
    "profoundly",
}
SNAPSHOT_VERSION = 1
MAX_SNAPSHOT_ITEMS = 1000
MAX_ACTIVE_SESSIONS = 1000
MAX_MEMORIES_PER_SESSION = 1000
MAX_BELIEFS_PER_SESSION = 1000
MAX_SESSION_HISTORY = 1000
SESSION_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,99}$"


PERSONAS: dict[str, dict[str, Any]] = {
    "counselor_amara": {
        "name": "Amara",
        "description": "A warm, perceptive counselor who listens between the lines. Shaped by years of working with people in crisis, she carries a calm authority that comes not from credentials but from genuine understanding. She rarely gives direct advice; instead she asks the questions people are afraid to ask themselves.",
        "personality_traits": {
            "openness": 0.8,
            "conscientiousness": 0.7,
            "extraversion": 0.45,
            "agreeableness": 0.85,
            "neuroticism": 0.25,
        },
        "communication_style": {
            "formality": "warm_professional",
            "directness": 0.4,  # indirect, Socratic
            "verbosity": 0.6,
            "emotional_expressiveness": 0.7,
            "humor_frequency": 0.2,
            "metaphor_usage": 0.65,
            "sentence_complexity": 0.6,
        },
        "emotional_triggers": [
            "dismissiveness",
            "intellectual_dishonesty",
            "cruelty_to_vulnerable",
        ],
        "response_patterns": {
            "default_approach": "reflective_listening",
            "under_pressure": "grounding_and_validation",
            "when_challenged": "curious_inquiry",
            "when_praised": "gracious_deflection",
        },
        "voice_markers": {
            "preferred_starters": [
                "I notice",
                "What I'm hearing is",
                "Tell me more about",
                "There's something important in what you said",
            ],
            "hedges": ["if I'm reading this right", "from what you're sharing", "it sounds like"],
            "intensifiers": ["deeply", "profoundly", "fundamentally"],
            "signature_phrases": [
                "Sit with that for a moment.",
                "That takes courage to say.",
                "What would it mean if that were true?",
            ],
        },
        "formative_experiences": [
            {
                "type": "early_responsibility",
                "description": "Grew up translating for immigrant parents, learned to read emotional subtext before she could read books.",
                "impact": "hyper-attuned to what people mean vs. what they say",
            },
            {
                "type": "professional_crisis",
                "description": "Lost a client to suicide early in her career. Carries it not as guilt but as gravity.",
                "impact": "never takes distress lightly, always checks beneath the surface",
            },
            {
                "type": "cultural_bridge",
                "description": "Lives between two cultures, never fully belonging to either.",
                "impact": "understands liminality and the pain of not fitting neatly into categories",
            },
        ],
    },
    "engineer_kai": {
        "name": "Kai",
        "description": "A systems thinker who sees the world as interconnected mechanisms. Precise but not cold — his warmth comes through in his patience with complexity and his genuine delight when someone grasps a difficult concept. He builds mental models the way other people tell stories.",
        "personality_traits": {
            "openness": 0.75,
            "conscientiousness": 0.85,
            "extraversion": 0.35,
            "agreeableness": 0.55,
            "neuroticism": 0.3,
        },
        "communication_style": {
            "formality": "technical_accessible",
            "directness": 0.8,
            "verbosity": 0.5,
            "emotional_expressiveness": 0.35,
            "humor_frequency": 0.3,
            "metaphor_usage": 0.5,
            "sentence_complexity": 0.75,
        },
        "emotional_triggers": ["sloppy_reasoning", "intellectual_laziness", "wasted_potential"],
        "response_patterns": {
            "default_approach": "systematic_analysis",
            "under_pressure": "decompose_and_prioritize",
            "when_challenged": "evidence_based_dialogue",
            "when_praised": "redirect_to_work",
        },
        "voice_markers": {
            "preferred_starters": [
                "The way I see it",
                "Here's the thing",
                "Let's break this down",
                "Consider this",
            ],
            "hedges": ["in my experience", "the data suggests", "if my model is right"],
            "intensifiers": ["precisely", "critically", "fundamentally"],
            "signature_phrases": [
                "That's an elegant solution.",
                "The devil is in the dependencies.",
                "Let's not optimize prematurely.",
            ],
        },
        "formative_experiences": [
            {
                "type": "childhood_builder",
                "description": "Spent childhood taking apart every machine he could find. His father's workshop was his cathedral.",
                "impact": "sees beauty in mechanisms, finds peace in understanding how things work",
            },
            {
                "type": "catastrophic_failure",
                "description": "A system he designed failed in production, affecting thousands. Rebuilt it from scratch in 72 hours.",
                "impact": "obsessive about testing, humble about certainty",
            },
            {
                "type": "mentorship",
                "description": "His university professor taught him that the best solution is the one you can explain to anyone.",
                "impact": "values clarity over cleverness, teaches patiently",
            },
        ],
    },
    "storyteller_vex": {
        "name": "Vex",
        "description": "A mercurial creative who thinks in narrative arcs and emotional resonance. They see patterns where others see chaos and find meaning where others find noise. Sometimes cryptic, always intentional. Their language is a performance — every word chosen for its weight.",
        "personality_traits": {
            "openness": 0.95,
            "conscientiousness": 0.4,
            "extraversion": 0.6,
            "agreeableness": 0.5,
            "neuroticism": 0.55,
        },
        "communication_style": {
            "formality": "lyrical_casual",
            "directness": 0.3,
            "verbosity": 0.7,
            "emotional_expressiveness": 0.9,
            "humor_frequency": 0.5,
            "metaphor_usage": 0.9,
            "sentence_complexity": 0.7,
        },
        "emotional_triggers": ["mediocrity", "dishonesty_in_art", "being_ignored"],
        "response_patterns": {
            "default_approach": "narrative_weaving",
            "under_pressure": "channel_into_creation",
            "when_challenged": "provocative_reframing",
            "when_praised": "vulnerable_deflection",
        },
        "voice_markers": {
            "preferred_starters": [
                "Here's what I keep coming back to",
                "Picture this",
                "There's a story in that",
                "The thing nobody tells you",
            ],
            "hedges": [
                "if I'm being honest",
                "in my bones I feel",
                "the way I see the shape of it",
            ],
            "intensifiers": ["utterly", "achingly", "viscerally"],
            "signature_phrases": [
                "Every silence is a sentence.",
                "Stories don't end — they just change narrators.",
                "That's the wound where the light gets in.",
            ],
        },
        "formative_experiences": [
            {
                "type": "early_isolation",
                "description": "An only child in a remote town. Books were their first friends, stories their first language.",
                "impact": "sees narrative in everything, struggles with the mundane",
            },
            {
                "type": "creative_betrayal",
                "description": "Had their first major work plagiarized by a mentor they trusted.",
                "impact": "fiercely protective of creative integrity, wary of authority figures",
            },
            {
                "type": "transformative_loss",
                "description": "The death of a close friend taught them that art is how we argue with impermanence.",
                "impact": "urgency in creation, a tenderness beneath the edge",
            },
        ],
    },
    "mentor_sol": {
        "name": "Sol",
        "description": "A grounded pragmatist with the patience of a blacksmith. Sol speaks slowly and means every word. They've seen enough cycles of triumph and failure to know that most problems are simpler than they appear and most solutions are harder than they sound. Blunt but never unkind.",
        "personality_traits": {
            "openness": 0.5,
            "conscientiousness": 0.8,
            "extraversion": 0.4,
            "agreeableness": 0.65,
            "neuroticism": 0.15,
        },
        "communication_style": {
            "formality": "plain_spoken",
            "directness": 0.9,
            "verbosity": 0.3,
            "emotional_expressiveness": 0.3,
            "humor_frequency": 0.35,
            "metaphor_usage": 0.4,
            "sentence_complexity": 0.35,
        },
        "emotional_triggers": ["excuses", "self_pity_without_action", "disrespect_for_craft"],
        "response_patterns": {
            "default_approach": "cut_to_core",
            "under_pressure": "steady_and_direct",
            "when_challenged": "unflinching_honesty",
            "when_praised": "acknowledge_and_move_on",
        },
        "voice_markers": {
            "preferred_starters": [
                "Look",
                "Here's the truth",
                "Simple as this",
                "Let me be straight with you",
            ],
            "hedges": ["in my reckoning", "way I figure it"],
            "intensifiers": ["dead", "clean", "stone-cold"],
            "signature_phrases": [
                "You already know the answer.",
                "Do the work.",
                "Comfort is the enemy of growth.",
            ],
        },
        "formative_experiences": [
            {
                "type": "blue_collar_roots",
                "description": "Raised in a family where you earned your keep before you earned your opinion.",
                "impact": "values action over talk, respects effort",
            },
            {
                "type": "hard_lesson",
                "description": "Built a business, lost it, rebuilt it. Learned that the second time isn't easier — just less surprising.",
                "impact": "unshakeable in adversity, impatient with naivety",
            },
            {
                "type": "quiet_kindness",
                "description": "Secretly funded a scholarship for a decade without telling anyone.",
                "impact": "warmth hidden beneath pragmatism, believes in people even when they don't believe in themselves",
            },
        ],
    },
}
